Pomme-Baya-Believers/atelier

server/controllers/controllerssean.js
server/index.js
server/routes/routessean.js

let me know if theres anything to add!

adding routes and controllers, imported in server/index.js

---

.babelrc
client/src/index.jsx
package-lock.json
server/index.js
webpack.config.js

we can now start on our individual components!

framework complete. client side website is rendering "test"

---

server/routes/routesdarrell.js

Add controllersdarrell and routesdarrell

controllersdarrell routesdarrell

---

client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/reviewtile.jsx
client/src/index.jsx

Hashed out basic framework for review list. Successfully getting data into reviewtile from API. Added ReviewList component to client side index.jsx
Currently ReviewList is using useEffect with hardcoded in parameters just for rendering data purposes. This will eventually take in whatever product is set as the state.

Basic reviewlist framework complete. 

---

client/src/components/reviews/apihelpers.jsx
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/reviewtile.jsx
client/src/index.jsx
server/controllers/controllersnaru.js
server/index.js
server/routes/routesnaru.js

Added server side controller and route for get requests to api/reviews. 
Hashed out basic framework for review list and review tile. Review tile is successfully receiving necessary data from the api and rendering it on the client side. 
I commented out lines in index.js and index.jsx specific to the review widget so these changes should not affect the overall framework currently set up. 
Sorry for the big commit. I promise I'll make future ones much smaller now that we have our process much more clear in my mind.

Hashing out review list

---

README.md
client/src/components/overview/overview.jsx
client/src/index.jsx
package-lock.json
server/controllers/contollermatthew.js
server/routes/routesmatthew.js

Added some baseline files for the Product Information Component

Product information

---

client/src/components/reviews/apihelpers.jsx
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/reviewtile.jsx
server/controllers/controllersnaru.js
server/routes/routesnaru.js

Styling changes based on airbnb linter. No actual code changed and confirmed still working as intended

Styling changes. No code changes.

---

client/src/components/reviews/reviewlist.jsx

Added button to show more reviews. Currently shows 2 reviews on intial render and clicking the button shows 2 more views. Need to add functionality which disables the button once there are no more reviews to show.

Simple button to increment count by 2 and show more reviews

---

.eslintrc.js
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/reviewtile.jsx
client/src/index.jsx

- Set my function definitions back to arrow functions now that linter ignores them as errors. 
- Changed rule in linter to ignore console.logs and console.errors. 
- ReviewList now accepts top level productID state.

Mostly styling changes

---

client/src/components/reviews/apihelpers.jsx
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/sort.jsx

- Added a new file to handle sorting reviews by relevant, newest, or helpfulness.
- Imported this function into main reviewList component
- Added new state 'sort' that is now passed into get request. (previously 'relevant' was hard coded in as this URL parameter)
- Added a useEffect in main reviewList component to re-render reviews when sorting option is changed

Sort By drop down menu for reviews

---

client/src/assets/styles.css
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/reviewtile.jsx

- Added ids and classes to most of my elements
- Added CSS styling in styles.css
- Review List and each review tile should now show a border
- Set display to flex for entire review list
- Still needs a lot more CSS but good enough for now

A little bit of css to make sub components more organized

---

client/src/assets/styles.css
client/src/components/reviews/newreview.jsx
client/src/components/reviews/reviewlist.jsx
server/index.js

- Most of the functionality is built out
- The new file newreview.jsx contains the modal form for submitting a new review. All required review points have been included as input fields. 
- Imported newreview.jsx into reviewlist.jsx
- Added a button to reviewlist.jsx to pop up the newreview modal form 
- Added css styling for the newly added button
- Have yet to touch the overall css styling for the form
- Need to figure out what to do with uploaded photos and how to render them as thumbnails
- Need to send meta data as a prop and determine what characteristics the form will show for review
- Need to write a api handler for posting the new review when user clicks submit

Modal form for writing a new review

---

client/src/components/overview/basicProductInfo.jsx
client/src/components/overview/overview.jsx
client/src/components/overview/overview.test.js
client/src/components/overview/productDescription.jsx
client/src/index.jsx
package.json

Functional Product Description and social media links.  Social media links are done by using react-share library.  I also added in the initial jest test to try it out.

1.1.1b product description

---

client/src/components/reviews/newreview.jsx
client/src/components/reviews/reviewlist.jsx
client/src/index.jsx
package.json

- Now making a get request with count 10000 for intiial render and sorting through these to actually display the reviews in order based on 'relevant', 'newest', or 'helpfulness'. 
- This is still relying on the API get request's native sort parameter to determine what is considered 'relevant', 'newest', or 'helpful'. (Newest is working as expected but I will need to check relevant and helpfulness to make sure the API's interpretation of each sort parameter is the same as the business requirements').
- Added a submit handler to newReview. Doing the same thing that was hard coded into the onSubmit within the <form> HTML element, but added two lines to close the form upon clicking submit, as well as emptying out the new review form's input fields. Decided to just write a submitHandler …

Refactored Sort

---

client/src/components/overview/basicProductInfo.jsx
client/src/components/overview/overview.jsx
client/src/components/overview/styleSelector.jsx
client/src/components/overview/styleThumbnail.jsx
client/src/components/starRating.jsx
client/src/index.jsx
server/controllers/controllersmatthew.js
server/routes/routesmatthew.js

Will need to do thumbnail styling for rounded thumbnails and checkmarks for currently selected style.

Functional but ugly Style Selector

---

client/src/assets/styles.css
client/src/components/reviews/newreview.jsx
client/src/components/reviews/productBreakdown.jsx
client/src/components/reviews/ratingbreakdown.jsx
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/reviewtile.jsx
client/src/components/reviews/sort.jsx

- Almost all changes here are CSS
- Overall review component should not have the proper layout with the rating breakdowns on the left and the reviews on the right.
- added some wrapping <divs>
- added some classnames and ids
- slight change to wording for characteristics descriptions (I think there is a type in the business doc section 1.2.6.3)

Organizing overall review component with CSS

---

client/src/assets/styles.css
client/src/components/reviews/newreview.jsx
client/src/components/reviews/productBreakdown.jsx
client/src/components/reviews/ratingbreakdown.jsx
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/reviewtile.jsx
client/src/components/reviews/sort.jsx

- Added a product breakdown component
- Imported component into reviewlist
- Component renders a rating bar for each characteristic associated with a product, e.g. comfort, quality, size
- Bar shows a light grey background with a down-pointing triangle positioned based on the overall rating.
- Above the bar is the associated characteristic
- Below the bar is the description for the scale, e.g. for a characteristic of comfort, 1 = uncomfortable and 5 = perfect
- Added css styles to make all of the above render properly
- Changed background color of rating bars in ratingBreakdown component to light grey to match productBreakdown component bars (light grey looks nicer I think).

Product breakdown component complete

---

client/src/components/reviews/reviewlist.jsx
client/src/index.jsx

- Simple conditional in reviewList.jsx to render the 'More Reviews' button if there actually are more reviews to show
- In other words, no longer renders the 'More Reviews' button if there are no more reviews to show.

More Reviews button renders on condition

---

client/src/assets/styles.css
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/DetailsModal.jsx
client/src/components/Related/EmptyProductCard.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/components/Related/RelatedWidget.jsx
client/src/components/overview/overview.jsx
client/src/index.jsx

I reworked the carousel to look more similar to the business doc layout. 
Not visible background, 
white-out on right side when near edge of window, 
removed empty space,
added in StarRatings (also changed css --star-size to 100%
Local storage handled within CarouselYourOutfit.
Currently can add 1 item, read item, and delete item.
Working on how to add multiple items to the same entry in localStorage.
Extremely similar to Carousel, but when empty, will show "add item" button.
Pull localStorage, map over it and create the list of items in the carousel.

Carousel lookin sexy /Local storage beginning

---

client/src/components/reviews/reviewtile.jsx
client/src/index.jsx

- Small implementation, only changed reviewTile.jsx to convert review data's timestamp to a human readable format

Timestamp of each review is now human readable (Month DD, YYYY)

---

client/src/components/reviews/reviewtile.jsx

- "I recommend this product" now has a checkmark icon next to it as per the business requirements.

Checkmark unicode added to review tiles

---

client/src/assets/styles.css
client/src/components/reviews/reviewtile.jsx
client/src/index.jsx

- Reviews have an option to upload photos
- If there are any photos, each photo is rendered as a thumbnail below the review body
- Clicking on a thumbnail opens a modal window that shows the full resolution photo
- Once the full resolution photo is displaying, clicking anywhere closes the modal.

Added photos to review tiles

---

client/src/assets/styles.css
client/src/components/reviews/reviewtile.jsx
client/src/index.jsx

- Sellers have the option to respond to reviews
- Added a div in each review tile to render the sellers response
- Added some CSS to show response with a light grey background to distinguish it from the original review.

Added Seller's response to each review tile

---

client/src/assets/styles.css
client/src/components/reviews/reviewtile.jsx
client/src/index.jsx

- On initial render, each review tile's body shows a max of 250 characters
- If the review body contains more than 250 characters, a 'Show more' button is also rendered
- On click of the 'Show more' button, the remainder of the review body is rendered and the 'Show more' button is hidden

Review Body rendering 250 characters max

---

client/src/assets/styles.css
client/src/components/Related/AddProductCard.jsx
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/EmptyProductCard.jsx
client/src/components/Related/MyOutfitCard.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/components/Related/RelatedWidget.jsx
client/src/index.jsx

Utilize localStorage.setItem('key', JSON.stringify(value)), and JSON.parse(localStorage.getItem('key')
Also, created a YourOutfitCarousel and YourOutfitCard components.
State is held in the widget, so the entire carousel updates as soon as the state changes.

1.4.4 your outfit adding and deleting

---

client/src/assets/styles.css
client/src/components/Related/AddProductCard.jsx
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/EmptyCard.jsx
client/src/components/Related/MyOutfitCard.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/components/Related/RelatedWidget.jsx
client/src/index.jsx

react-spinners part of PACKAGE.JSON
Created EmptyCard component
Removed clutter in AddProductCard, RelatedProductsCard, and MyOutfitCard
4 Empty cards with loading rendered while waiting for product images query.
AddItem Card now rendering image and MainProduct name.

EmptyCard given loading bar, Addcard rendering mainProduct Image

---

client/src/assets/styles.css
client/src/components/Related/AddProductCard.jsx
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/EmptyCard.jsx
client/src/components/Related/MyOutfitCard.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/components/Related/RelatedWidget.jsx
client/src/index.jsx

All my components currently pass the Linter
PLEASE DO NOT accept this PR until my previous, #51 has been accepted? 
I have to imagine, if this one was pulled first, then it would undo my tidying... not exactly sure how that works.

Card cleanup

---

client/src/assets/styles.css
client/src/components/reviews/newreview.jsx
client/src/components/reviews/reviewlist.jsx
client/src/index.jsx

- I know this looks like a lot but most of the changes are  CSS additions and class/ID changes or HTML element changes, e.g. making a <h5> into a <div> for formatting purposes. 
- The actual functional change was on the new review form: making the radio buttons into stars for rating 1 - 5
- Added 3 handlers for mouseover, mouseout, and mouseclick to make star ratings render properly in the new review form.

New Review Form CSS mostly done

---

client/src/assets/styles.css
client/src/components/reviews/apihelpers.jsx
client/src/components/reviews/reviewtile.jsx
client/src/index.jsx
server/controllers/controllersnaru.js
server/routes/routesnaru.js

- New apihelper, route, and controller for PUT request 
- Each review tile has a helpfulness rating displayed
- Clicking on Yes makes a PUT request to the API to increase helpfulness rating
- Clicking on No does NOT make any requests to the API since the API does not store this data
- Some CSS effects for hovering and clicking Yes/NO

Clicking Yes/No for helpfulness

---

client/src/assets/styles.css
client/src/components/reviews/newreview.jsx

- Just a few lines edited
- Placeholders for input fields and tips for inputs described by business requirements.

Added some placeholders and tips for inputs

---

client/src/assets/styles.css
client/src/components/PriceStrike.jsx
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/MyOutfitCard.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/components/Related/RelatedWidget.jsx
client/src/index.jsx

I added a price strikethrough component that can receive product/ID/styles and render a price based on the default? style.  
Or if passed a  specific style as a prop
Will render the default price, and if there is a sale_price as well, it will show both with the default struckthrough

Strikethrough price

---

client/src/assets/styles.css
client/src/components/overview/overview.jsx
client/src/components/reviews/reviewlist.jsx
client/src/index.jsx

- useEffect is now watching productID
- changed overall doc font to sans-serif

Changes we made together

---

client/src/components/reviews/reviews.test.js
package.json

- Still need to add more tests to increase coverage

Added some tests for ratings and reviews

---

client/src/components/overview/overview.test.js

Overview Tests

---

client/src/components/reviews/reviews.test.js
client/src/components/reviews/reviewtile.jsx

- % functionality is at 56% but everything else is >70%

Achieving >70% line coverage for Ratings and Reviews

---

client/src/assets/styles.css
client/src/components/reviews/ratingbreakdown.jsx

- Overlooked this in the business requirements

Added total rating count to rating breakdown

---

client/src/assets/styles.css
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/reviewtile.jsx

- Review component now has a Search input field
- Search term is stored in a state at the top level component
- Review tiles are rendered based on if the summary or body contains the search term
- Created another state to store number of reviews that were rendered before searching so the same view can be set once the search field is cleared.

Search bar complete

---

client/src/components/reviews/reviews.test.js

- Added an input prop to ReviewTile component in previous PRs
- Included this prop in my tests
- All tests now pass.

Added new prop to ReviewTile tests

---

client/src/components/PriceStrike.jsx
client/src/components/Related/AddProductCard.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/MyOutfitCard.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/components/Related/related.test.js

utilizing click events to dig into more lines in AddProductCard

passing 70% of lines

---

client/src/components/reviews/newreview.jsx
client/src/components/reviews/reviewlist.jsx
client/src/index.jsx

- Got rid of get request for product info
- passing mainData from index.js to reviewlist component

using mainData from index.js

---

client/src/assets/styles.css
client/src/components/Related/AddProductCard.jsx
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/index.jsx

some css, some JS. But until we find an issue, i think the styles look good on the carousels and i'm onto accessibility!

Carousel Final styles1.0

---

client/src/assets/styles.css
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/sort.jsx
client/src/index.jsx

- Footer on overall app
- Contains hyperlinks to our linkedIns.

App footer

---

client/src/assets/styles.css
client/src/components/reviews/reviewlist.jsx
client/src/components/reviews/sort.jsx

- Resetting top level component states when productID changes, in order to revert back to default view for the Ratings and Review
- Had to add some functionality to ensure default view is rendered on productID change
- Some styling additions

Added side effects to productID changing

---

client/dist/index.html
client/src/assets/styles.css
client/src/components/PriceStrike.jsx
client/src/components/Related/AddProductCard.jsx
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/MyOutfitCard.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/index.jsx

Added tabIndex to every tile and actionButton in the carousel, AND arrows.
Also added altText to images
And lang='en' in. index.html

Final style1.2 / Accessbility

---

client/src/assets/styles.css
client/src/index.jsx

- Added a header for the overall app
- Added dark mode
- Feel free to edit

Header for overall App

---

client/src/assets/styles.css

I changed like 1 line of code thank you for setting up the infrastructure or night Mode

nightMode in RelatedTiles

---

client/src/assets/styles.css

- I think Sean's previous PR overwrote a couple of my styling changes for dark mode. Fixed. (My fault for reviewing too quickly)

Small edits for darkmode

---

client/src/assets/styles.css
client/src/components/Related/DetailsModal.jsx
client/src/index.jsx

retlatedDetails modal night mode
actionButton night mode

Final style2.4

---

client/src/index.jsx

to make standout from background  more during dark mode

Persistent Dark Mode, and --tile style implementation

---

client/src/assets/styles.css
client/src/index.jsx

Made the header stay in position as you scroll down the page.  Thought it would be attractive. 
Could also put our linkedIn's inside that so they are always visible during demo, standing in for different categorical buttons to click

Fixed header

---

client/src/assets/styles.css
client/src/index.jsx

- Realized New Review form was not being affected properly by darkmode.

Darkmode for newreview from

---

client/src/assets/styles.css
client/src/index.jsx

please refer to the title of PR

clickable Header linkdIns

---

client/src/assets/styles.css

- Was looking weird in the footer

Changed "members" background color to color

---

client/src/assets/styles.css

Main Image looks great already!... I just can't stop myself from doing a little CSS.

some box shadow, and  a little margin around overviewMainPic

---

client/src/assets/styles.css
client/src/components/Related/Carousel.jsx
client/src/index.jsx

Final style3.0

---

client/src/assets/styles.css
client/src/components/Related/RelatedWidget.jsx
client/src/index.jsx

Added small border lines in over section to unify aesthetic to the rest of the page.  
Attempted position:sticky for cool scrolling of headers but it ended up not looking good, so reverted to position:fixed.

Final style3.2

---

client/src/assets/styles.css
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/components/Related/RelatedWidget.jsx
client/src/index.jsx

React.createContext implemented in index.jsx
Provider component wrapping entire app in index.jsx
Ready for useContext to be utilized within ANY COMPONENT OF THE APP!!!

Context2.0

---

client/src/assets/styles.css
client/src/components/Related/AddProductCard.jsx
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/RelatedProductCard.jsx
client/src/components/Related/RelatedWidget.jsx
client/src/index.jsx

Now AddProductCard vanishes, and turns into MyOutfitCard on click. A smoother way of preventing double adds of the same product.

AddMyOutfit replaced with MyOutfitCard on Click

---

client/src/assets/styles.css
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/RelatedProductCard.jsx

Made the carousels scrollable. slightly less visually appealing, but removes the possibility of app failure due screen resizing/scrolling through carousel.
reduces api calls only when product ID changes, not during interaction with carousels
up next, scroll 1 tile on click

Nicer header and scrollable carousels.

---

client/src/assets/styles.css
client/src/components/Related/Carousel.jsx
client/src/components/Related/CarouselYourOutfit.jsx
client/src/components/Related/RelatedProductCard.jsx

Click and draggable carousel, utilized cursor:grab; to indicate grab-ability

Post presentation1.1
